### PR TITLE
feat: Add example weather extension

### PR DESCRIPTION
**Pull request by AdamHillier**

### CODE REVIEW

**Review by rlr — APPROVED** [review]
pretty straightforward. looks good to me! do you want me to try to run it locally? are there some docs on how to do it?

**Comment by AdamHillier** [comment]
Thanks :) Sure, if you want to run it locally there are some (sparse) docs [here](https://github.com/mozilla/newtab-webextensions/blob/master/README.md). You'll need to use AS master as recent changes haven't been exported to nightly yet. Oh and the experiment is a legacy addon so you need to re-enable them in about:config. Then you can install both the experiment and any of the demo extensions as temporary addons in about:debugging

**Comment by piatra** [comment]
@AdamHillier why is it a legacy addon? If we're merging this into newtab-webextensions shouldn't they all "just work"™?

**Comment by AdamHillier** [comment]
@piatra Well this is a WebExtension, not a legacy addon. It's just the experiment that provides the API that is. That's just the way the API Experiments work, I mentioned that maybe there should be an exception in Firefox for Experiments to the WebExtensions team.... If the API gets shipped then it won't be an issue anymore and these extensions will "just work" :)

**Pull request merged**
